### ISSUE TITLE
Add labels to allowlist entries

### ISSUE THREAD

**Issue by fllaca** [ConsenSys/permissioning-smart-contracts#180]
When the allow lists (both accounts and nodes) grow, it's difficult to tell which enode corresponds to each ethereum node. Adding a string label to each item in the allowlist (along with the enode  or account address) would make easier for the administrators to maintain (add/revoke) the entries in the allow lists.

**Comment by macfarla** [comment]
This sort of metadata (other useful data eg date added, who added them) could be stored by the dapp, offchain in a simple database ie without needing to change the contracts.

**Comment by MadelineMurray** [comment]
@fllaca - see comments above. Is that approach an option for your use-case?

**Comment by fllaca** [comment]
@macfarla @MadelineMurray yes, that makes sense, thanks! Is it planned to include such feature in the dapp in this project?

**Comment by MadelineMurray** [comment]
@fllaca - adding this feature isn't on our short term roadmap unfortunately.  If you're interested in implementing the feature yourself, another option would be to extend the permissioning contracts to add a label field and update the dapp to read from the contract and display this label.

**Comment by macfarla** [comment]
@fllaca we are not going to progress this feature. Closing this issue.
