### ISSUE TITLE
Version v2 of permissioning smart contracts

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/permissioning-smart-contracts#193]
v2 of permissioning smart contracts will conform to v6 of the EEA client specification. 

** Done criteria** 

- [x] get development environment set up to be able to build and run tests
- [x] clean up some annoying things
- [x] remove deprecated options in preparation for v2
- [x] update dependencies
- [x] Update permissioning contracts 
- [x] Update dapp
- [x] Test that Besu permissioning still works with nodes added / removed via the updated contracts + dapp
- [x] Update release notes for v1.1.0 to state it's v1 of the contracts as specified in Besu and conforms to v5 of the EEA spec. 
- [x] Release v2.0 with release notes: that it's v2 of the contracts as specified in Besu and conforms to v6 of the EEA spec.

**Comment by macfarla** [comment]
Updated release notes for v1.1.0 https://github.com/ConsenSys/permissioning-smart-contracts/releases/tag/v1.1.0
