### ISSUE TITLE
Please update the docker hyperledger/besu registry

### ISSUE THREAD

**Issue by MWaser** [ConsenSys/permissioning-smart-contracts#209]
It currently has version 20.10.0 from 3 months ago

 New permissioning system (released Dec 16, 2020) requires 20.10.1+
 
 It would be nice to have 20.10.4

**Comment by macfarla** [comment]
Hi @MWaser this isn't anything to do with the permissioning-smart-contracts repo and I think you've solved your problem but reach out if you still have issues! Closing this issue.
