### ISSUE TITLE
Upload package to npm so contract can be imported from other projects

### ISSUE THREAD

**Issue by nmvalera** [ConsenSys/permissioning-smart-contracts#218]
#### Summary

Publish the package to npm so Smart Contracts can be imported from Solidity without having to clone the repo.

#### Acceptance Criteria

- [x] Create package on npm
- [ ] Set-up CI/CD pipeline to publish to npm

#### Reference

- [OpenZeppelin doc](https://docs.openzeppelin.com/contracts/2.x/#overview)

**Comment by macfarla** [comment]
NPM https://www.npmjs.com/package/permissioning-smart-contracts

**Comment by macfarla** [comment]
published to https://www.npmjs.com/package/@consensys-software/permissioning-smart-contracts
and can be imported like so:
```
import "@consensys-software/permissioning-smart-contracts/contracts/AccountRulesProxy.sol";
import "@consensys-software/permissioning-smart-contracts/contracts/Ingress.sol";


contract Alice is Ingress {
```

**Comment by macfarla** [comment]
How to publish:
https://www.npmjs.com/package/@consensys-software/permissioning-smart-contracts 
Prerequisites

- You need an npmjs account
- You need to be a collaborator ie member of consensys-software org

Note this project uses yarn not npm but it works much the same:
```
yarn login
yarn publish --access public
```
