### ISSUE TITLE
Dapp to allow domain names as well as IP

### ISSUE THREAD

**Issue by pinges** [ConsenSys/permissioning-smart-contracts#226]
### Description
The Dapp should enable the user to use domain names as well as IP addresses to identify p2p clients
### Acceptance Criteria
* Domain names can be added to permit p2p connections
   (Sally reported that this is possible already, but if possible add a test)
* Make sure that the UI clearly states that IP addresses and DNS can be used

**Comment by macfarla** [comment]
There is already a test for this - can add node3 with DNS host https://github.com/ConsenSys/permissioning-smart-contracts/blob/a5a0a6e5e791248b896f8de457e3b0ffd0227306/test/test-node-rules-list.js#L14
