### ISSUE TITLE
Clarify the criteria of version field included in the Smartcontracts

### ISSUE THREAD

**Issue by alberto-hernandez** [ConsenSys/permissioning-smart-contracts#256]
The NodeIngresss, NodeRules, AccountIngress and Account Rules contract contains a field named version.
This field in some smartcontracts takes the value equivalent 1.0.0 but in another 3.0.0.

Could you please clarify the criteria of the versioning taking in account that the actual permissioning package is 2.1.X?

Regards

**Comment by macfarla** [comment]
2.1 is the version of the package itself. The individual contracts also have their own version number that can be queried directly (and maybe this is not really required). They are totally unrelated to each other.
