### ISSUE TITLE
Clarification on Different IP Addresses for Node Ingress and Egress

### ISSUE THREAD

**Issue by ItayPodhajcer** [ConsenSys/permissioning-smart-contracts#257]
Some `k8s` implementation use two different addresses for ingress and egress:
1. Load balancer IP address (ingress)
2. NAT gateway IP address (egress)

In our tests, when whitelisting the node only with the load balancer's IP, the node couldn't connect to the network, as the IP address that was being used by the node when trying to connect to the boot nodes, was the NAT gateway's IP, which wasn't whitelisted.
Next, we tried whitelisting the same public key twice, once with the load balancer's IP and once with the NAT gateway's IP, and that solve the problem.

My question is whether you foresee any possible issues that by arise by using such a work around?

**Comment by ItayPodhajcer** [comment]
> We can add something to the docs about this

Yes, thanks!!

**Comment by macfarla** [comment]
Thanks for the reply @ItayPodhajcer - closing this one. The docs change will be done separately

**Comment by aertoria** [comment]
@macfarla 

Besides whitelisting, can you confirm that, has asymmetric IP for ingress and egress won’t cause other problems after POS upgrade? Thanks
