### ISSUE TITLE
Not able to do yarn install

### ISSUE THREAD

**Issue by victoryeo** [ConsenSys/permissioning-smart-contracts#284]
The error is:
An unexpected error occurred: "ENOENT: no such file or directory, open '/home/vic/.cache/yarn/v6/npm-@zondax-filecoin-signing-tools-0.2.0-8f8e92157cac2556d35cab866779e9a8ea8a4e25/node_modules/@zondax/filecoin-signing-tools/.yarn-metadata.json'".

Using yarn version 1.22.5

i did yarn cache clean. still getting the same error.

**Comment by macfarla** [comment]
I don't think this is an issue with permissioning-smart-contracts but with your yarn cache - can you try the steps here if you are still having issues ->> https://github.com/yarnpkg/yarn/issues/5275
