### ISSUE TITLE
Can't deploy smart contracts

### ISSUE THREAD

**Issue by RickCastle2018** [ConsenSys/permissioning-smart-contracts#291]
I created `.env` file following [this guide](https://besu.hyperledger.org/en/stable/private-networks/tutorials/permissioning/onchain/#11-deploy-the-contracts) and tried to deploy smart contracts with `yarn truffle migrate --reset`, and I got this error:

![image](https://user-images.githubusercontent.com/48931166/186876905-ef53f6a1-10f4-431b-a170-d476c3eee4f6.png)

The script simply couldn't load environment variables. I've tried to set them right in the `truffle-config.js`, but it unfortunately didn't help.

Could you explain, what I'm doing wrong?

P.S. Setup config: I have deployed besu on server (not locally) as it had been written in the guide.

**Comment by RickCastle2018** [comment]
It seems like I have the same #255 issue. And I'm sure about having the `.env` file in the right place. This issue is a blocking thing in my project, and I'm afraid I'm not the only one. @macfarla, let's try to resolve this together.

**Comment by vittoriocapocasale** [comment]
The truffle-config.js file exports two networks: besu and granache. This is what worked for me:
`yarn truffle migrate --reset --network=besu
`

**Comment by macfarla** [comment]
yes by default the develop network is used.
