### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by macfarla** [ConsenSys/permissioning-smart-contracts#301]
This repository is being archived.

You can still use onchain permissioning with [Besu](https://besu.hyperledger.org/en/stable/Tutorials/Permissioning/Getting-Started-Onchain-Permissioning/ - will remove references there to the dapp) however we do not plan to further develop either the specific implementation of these contracts or the dapp that is contained in this repository.

Additionally, due to outdated dependencies, the instructions in the README to build and run the dapp may not work for new users (only work for existing users).

**Comment by macfarla** [comment]
@edumar111 I think this won't affect your use case since you already maintain your own fork of this repo with some extra features - but tagging you just in case

**Comment by antonydenyer** [comment]
@albert0-hernandez fyi
